### ISSUE TITLE
请问这个可以部署到腾讯云 cos 吗？

### ISSUE THREAD

**Issue by jsyt** [saltbo/uptoc#1]

**Comment by saltbo** [comment]
目前还不可以，后续可能会支持。当然，也欢迎提交PR

**Comment by saltbo** [comment]
查了一下 官方有提供SDK https://github.com/tencentyun/cos-go-sdk-v5

使用该sdk实现一个COS的Uploader就可以了

**Comment by jsyt** [comment]
嗯，官方有提供相应的 github action ，感觉 这个也很方便

**Comment by saltbo** [comment]
现在已经支持COS了，同时也支持GitHubAction，使用uptoc以后换平台也会非常方便。欢迎体验~
