### ISSUE TITLE
aws-sdk module download不了。能否支持goproxy

### ISSUE THREAD

**Issue by xiaods** [saltbo/uptoc#31]
![Image_20211102093706](https://user-images.githubusercontent.com/37678/139772701-7ebf7f8b-c160-40f9-9de2-ac68c0ca1445.png)

是否在你的action中支持下Goproxy.cn 完全实现了GOPROXY 协议

**Comment by saltbo** [comment]
这是偶发的吧，重试下呢？  gha是运行在国外，不需要goproxy啊

**Comment by xiaods** [comment]
因为我挂了一个self hosted节点，在国内跑

Ambor ***@***.***> 于 2021年11月2日周二 下午2:41写道：

**Comment by saltbo** [comment]
我去 这玩意儿还能自建节点啊

那得支持下设置环境变量了

**Comment by xiaods** [comment]
你玩玩先。时代不同了。
