### ISSUE TITLE
七牛云上传相同文件报错

### ISSUE THREAD

**Issue by geekeren** [saltbo/uptoc#6]
当重复上传相同内容的文件到七牛云时会发送pipeline运行失败：
![image](https://user-images.githubusercontent.com/13082375/82132683-f37c5100-9814-11ea-8e15-595f664654c0.png)

- 日志信息

![image](https://user-images.githubusercontent.com/13082375/82132661-a6987a80-9814-11ea-932c-974d044ba969.png)

- Github Action 代码:

![image](https://user-images.githubusercontent.com/13082375/82132669-bdd76800-9814-11ea-96c4-dff2058f44c6.png)

**Comment by geekeren** [comment]
这三个文件和云上版本应该是一样的，但是依旧显示`found 3 files to be uploaded, uploading...`, 我想是不是检测文件是否相同的逻辑有点问题？

**Comment by saltbo** [comment]
是的，这个问题确实存在。

文件是否一致的比较依赖的是ETag，正常来说ETag就是文件的Md5值，但是七牛的ETag他们自己实现了一套算法。这个问题本来我开发的时候就了解到了，但是七牛的SDK里写的是Hash，我以为那个Hash是Md5而不是他们的ETag，但我晚上测试了一下Hash=ETag。。。

**Comment by saltbo** [comment]
我查了七牛的API手册，发现他们也会返回一个MD5，但是他们的SDK里又没有那个字段。

经过V2er的提醒可以统一使用S3协议，所以我也不打算用七牛的sdk了，直接用S3操作七牛了，这回就没这个问题了。

**Comment by saltbo** [comment]
v1.2.9已发布 你可以再试一下 @geekeren

**Comment by saltbo** [comment]
发现通过S3上传还得设置Content-Type，修复了一下，重新发了v1.3.0

**Comment by geekeren** [comment]
问题解决了，感谢这些快的响应力

**Comment by saltbo** [comment]
哈哈 第一个开源项目 必须得积极
