### ISSUE TITLE
support ignore

### ISSUE THREAD

**Issue by eallion** [saltbo/uptoc#9]
建议增加 ignore 或者类似的指令，以排除某些大文件或文件夹。谢谢！

**Comment by saltbo** [comment]
Already supported. thanks for your suggest.

example: `--exclude=.cache,test`

**Comment by eallion** [comment]
Thank you! Awesome!

**Comment by eallion** [comment]
But it doesn't work for the `.git` and `.github`

![hR51k9fmrF](https://user-images.githubusercontent.com/1698841/83989220-4ced2100-a978-11ea-9281-a54b58161ab5.png)

the workflow file : 

![gTqVUFOwaP](https://user-images.githubusercontent.com/1698841/83989245-61c9b480-a978-11ea-8678-4687fa8caa59.png)

**Comment by saltbo** [comment]
`/entrypoint.sh: line 5: ARGS+= --exclude ./.git,./.github: not found`

Sorry, test at local, but it's a bug for the entrypoint.sh on the GithubAction.

I will fix it later.

**Comment by saltbo** [comment]
@eallion fixed, rerun please.

**Comment by eallion** [comment]
ok thanks

**Comment by eallion** [comment]
@saltbo 

Get the same issue:

![CFfgm5R8J3](https://user-images.githubusercontent.com/1698841/83996474-db6c9d00-a98e-11ea-9617-3263d855f412.png)

**Comment by eallion** [comment]
And some other error:
```
Docker build failed with exit code 1, back off 8.81 seconds before retry.
```
> <https://github.com/eallion/favorite/runs/748740787>

**Comment by saltbo** [comment]
https://github.com/saltbo/uptoc/blob/master/core/engine.go#L112

fixed for the dist `./`, try again.

**Comment by eallion** [comment]
perfect
